# Makefile for exercise 1
CC=gcc

all: problem1 problem2 problem3

problem1:
	$(CC) problem1.c -lm -o problem1

problem2:
	$(CC) problem2.c -o problem2 

problem3:
	$(CC) problem3.c -o problem3

clean:
	rm problem1 problem2 problem3

.PHONY: clean all
